"""
GlowWise AI - Data Preprocessing Notebook Generator
Generates and executes the 02_data_preprocessing.ipynb notebook.
"""

import nbformat as nbf
from nbconvert.preprocessors import ExecutePreprocessor
from pathlib import Path
import sys

def main():
    print("=== Generating Data Preprocessing Notebook ===")
    
    # Resolve project root path
    current_path = Path(__file__).resolve()
    root_dir = current_path.parents[2]
    
    nb = nbf.v4.new_notebook()
    cells = []
    
    # Title & Overview
    cells.append(nbf.v4.new_markdown_cell("""# GlowWise AI - Data Preprocessing Pipeline 🧪

This notebook documents and executes the data preprocessing pipeline designed to prepare the Sephora skincare review dataset for machine learning. 

### Why Preprocessing Matters
Raw user reviews are unstructured, contain HTML/markdown artifacts, varying casings, and missing metadata values. More importantly, the dataset exhibits a severe class imbalance (~82% positive ratings) and multiple critical data leakage columns.

Preprocessing ensures:
1. **Target Engineering**: Constructing clean 3-class sentiment (`sentiment_label`) and binary satisfaction (`high_satisfaction`) targets.
2. **Leakage Elimination**: Removing columns like `rating` and `is_recommended` which create trivial model shortcuts, and post-review interaction statistics (`helpfulness`, feedback counts) which are unavailable at inference time.
3. **Data Completeness**: Handling missing values using median imputation for prices, "unknown" for user skin attributes, and empty strings for text metadata.
4. **Text Uniformity**: Cleaning text (lowercasing, whitespace cleanup) and merging reviews to form a single, unified text corpus (`combined_text`).
5. **Feature Engineering**: Creating character count (`text_length`) and word count (`word_count`) features.
6. **Efficiency**: Sampling a stratified 100,000 review dataset (`glowwise_reviews_sample_100k.csv`) to speed up model experiments while keeping the distribution identical to the full dataset.
"""))

    # Imports and Styling
    cells.append(nbf.v4.new_code_cell("""import sys
import json
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Adjust styling for clean premium visual aesthetics
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['text.color'] = '#332633'
plt.rcParams['axes.labelcolor'] = '#332633'
plt.rcParams['xtick.color'] = '#332633'
plt.rcParams['ytick.color'] = '#332633'

# Premium color variables matching the GlowWise wellness theme
COLOR_PLUM = '#3B243B'
COLOR_GOLD = '#C39B6F'
COLOR_ROSE = '#E8D3C4'
COLOR_LIGHT_PLUM = '#5C3D5C'
COLOR_CREAM = '#FCFAF7'
COLOR_MUTED = '#6E5C6E'

# Resolve project root path dynamically
current_path = Path.cwd().resolve()
root_dir = None
for parent in [current_path] + list(current_path.parents):
    if (parent / "README.md").exists():
        root_dir = parent
        break
if root_dir is None:
    root_dir = current_path.parent if 'notebooks' in current_path.name else current_path

sys.path.append(str(root_dir / "ml" / "src"))
from load_data import get_data_dir

# Set output path for figures
figures_dir = root_dir / "ml" / "reports" / "figures"
figures_dir.mkdir(parents=True, exist_ok=True)
"""))

    # Load Audited Dataset
    cells.append(nbf.v4.new_markdown_cell("""## 1. Load Audited Preprocessed Dataset

To keep execution efficient and fast, we load the **stratified 100k sample** generated by our preprocessing pipeline. Because this sample is stratified based on the target variable (`high_satisfaction`), its distribution perfectly reflects the full 1.09-million reviews dataset.
"""))

    cells.append(nbf.v4.new_code_cell("""data_dir = get_data_dir()
sample_path = data_dir / "processed" / "glowwise_reviews_sample_100k.csv"

print(f"Loading preprocessed sample: {sample_path.name}")
df = pd.read_csv(sample_path)
print(f"Dataset shape: {df.shape}")
df.head(3)
"""))

    # Verify target creation
    cells.append(nbf.v4.new_markdown_cell("""## 2. Target Variables & Class Distributions

We engineered two primary target variables:
- **`high_satisfaction`**: Binary indicator where rating 4-5 is mapped to `1` (High satisfaction) and rating 1-3 is mapped to `0` (Low/Medium satisfaction).
- **`sentiment_label`**: 3-class target classifying reviews into `positive`, `neutral`, and `negative`.

Let's look at the counts and percentages.
"""))

    cells.append(nbf.v4.new_code_cell("""print("=== High Satisfaction (Binary Target) ===")
hs_counts = df["high_satisfaction"].value_counts()
hs_pcts = df["high_satisfaction"].value_counts(normalize=True) * 100
for idx in hs_counts.index:
    print(f"Class {idx}: {hs_counts[idx]:,} reviews ({hs_pcts[idx]:.2f}%)")

print("\\n=== Sentiment Label (3-Class Target) ===")
sent_counts = df["sentiment_label"].value_counts()
sent_pcts = df["sentiment_label"].value_counts(normalize=True) * 100
for idx in sent_counts.index:
    print(f"Class {idx}: {sent_counts[idx]:,} reviews ({sent_pcts[idx]:.2f}%)")
"""))

    # Visualizing High Satisfaction
    cells.append(nbf.v4.new_markdown_cell("""### Visualizing Class Distribution: High Satisfaction
"""))

    cells.append(nbf.v4.new_code_cell("""fig, ax = plt.subplots(figsize=(6, 4))
bars = ax.bar(['High Satisfaction (1)', 'Low/Med Satisfaction (0)'], 
              [hs_counts[1], hs_counts[0]], 
              color=[COLOR_PLUM, COLOR_GOLD], edgecolor=COLOR_PLUM, width=0.5)

# Add values on top of bars
for bar in bars:
    height = bar.get_height()
    ax.annotate(f'{height:,}\\n({height/len(df)*100:.1f}%)',
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 3),  # 3 points vertical offset
                textcoords="offset points",
                ha='center', va='bottom', fontsize=10, fontweight='bold')

ax.set_title('High Satisfaction (Binary Target) Distribution', fontsize=12, pad=15, fontweight='bold', color=COLOR_PLUM)
ax.set_ylabel('Number of Reviews', fontsize=10)
ax.set_ylim(0, max(hs_counts) * 1.15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.savefig(figures_dir / "preprocessing_high_satisfaction.png", dpi=150, bbox_inches='tight')
plt.show()
"""))

    # Visualizing Sentiment
    cells.append(nbf.v4.new_markdown_cell("""### Visualizing Class Distribution: Sentiment Label
"""))

    cells.append(nbf.v4.new_code_cell("""fig, ax = plt.subplots(figsize=(7, 4.5))
classes = ['positive', 'negative', 'neutral']
counts = [sent_counts.get(c, 0) for c in classes]

bars = ax.bar(classes, counts, color=[COLOR_PLUM, COLOR_MUTED, COLOR_ROSE], edgecolor=COLOR_PLUM, width=0.5)

# Add values on top of bars
for bar in bars:
    height = bar.get_height()
    ax.annotate(f'{height:,}\\n({height/len(df)*100:.1f}%)',
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 3),
                textcoords="offset points",
                ha='center', va='bottom', fontsize=10, fontweight='bold')

ax.set_title('Sentiment Label (3-Class Target) Distribution', fontsize=12, pad=15, fontweight='bold', color=COLOR_PLUM)
ax.set_ylabel('Number of Reviews', fontsize=10)
ax.set_ylim(0, max(counts) * 1.15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.savefig(figures_dir / "preprocessing_sentiment.png", dpi=150, bbox_inches='tight')
plt.show()
"""))

    # Remove leakage columns
    cells.append(nbf.v4.new_markdown_cell("""## 3. Data Leakage Verification

Data leakage occurs when models learn from features that won't be available at test-time, or that are trivial duplicates of the target.
We verify that all leakage-prone columns have been successfully removed:
- `rating` (used only to engineer the targets)
- `is_recommended`
- `helpfulness`
- `total_feedback_count`
- `total_pos_feedback_count`
- `total_neg_feedback_count`
"""))

    cells.append(nbf.v4.new_code_cell("""leakage_cols = [
    "rating", "is_recommended", "helpfulness", 
    "total_feedback_count", "total_pos_feedback_count", "total_neg_feedback_count"
]

print("Verifying absence of leakage columns:")
found_leakage = [col for col in leakage_cols if col in df.columns]
if not found_leakage:
    print("✅ Success! No data leakage columns are present in the ML dataset.")
else:
    print(f"❌ Warning: The following leakage columns were found: {found_leakage}")
"""))

    # Missing Value Handling
    cells.append(nbf.v4.new_markdown_cell("""## 4. Missing Values Inspection After Imputation

The pipeline handled missing values as follows:
- **Text features** (`review_text`, `review_title`, `combined_text`, `ingredients`): replaced `NaN` with `""`.
- **User attribute categorical features** (`skin_type`, `skin_tone`, `hair_color`, `eye_color`): replaced `NaN` with `"unknown"`.
- **Numeric feature** (`price_usd`): coerced values to numeric and filled `NaN` with the median price from the training distribution ($39.00).

Let's check the missing value counts across all features.
"""))

    cells.append(nbf.v4.new_code_cell("""missing_counts = df.isnull().sum()
print("Missing counts per column after preprocessing:")
print(missing_counts)
"""))

    # Visualizing Missing Values
    cells.append(nbf.v4.new_markdown_cell("""### Visualizing Data Completeness
We visualize the missing values after preprocessing. Every column should display 0 missing values.
"""))

    cells.append(nbf.v4.new_code_cell("""fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(missing_counts.index, missing_counts.values, color=COLOR_PLUM, edgecolor=COLOR_PLUM)
ax.set_title('Missing Values per Feature After Preprocessing', fontsize=12, pad=15, fontweight='bold', color=COLOR_PLUM)
ax.set_ylabel('Number of Missing Rows', fontsize=10)
ax.set_xticklabels(missing_counts.index, rotation=45, ha='right', fontsize=9)
ax.set_ylim(0, 10) # Set a low limit since all values are 0
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.savefig(figures_dir / "preprocessing_missing_values_after.png", dpi=150, bbox_inches='tight')
plt.show()
"""))

    # Text properties analysis
    cells.append(nbf.v4.new_markdown_cell("""## 5. Text length and Word Count Analysis

We engineered two features from `combined_text`:
- `text_length`: Number of characters.
- `word_count`: Number of words.

Let's evaluate their statistical summaries.
"""))

    cells.append(nbf.v4.new_code_cell("""df[['text_length', 'word_count']].describe()"""))

    # Visualizing Text Length
    cells.append(nbf.v4.new_markdown_cell("""### Visualizing Text Length Distribution
We display a histogram showing the distribution of review character lengths. Since some reviews can be extremely long, we clip the x-axis at 1,500 characters for readability.
"""))

    cells.append(nbf.v4.new_code_cell("""fig, ax = plt.subplots(figsize=(8, 4))
ax.hist(df['text_length'], bins=50, range=(0, 1500), color=COLOR_PLUM, edgecolor=COLOR_CREAM, alpha=0.9)
ax.axvline(df['text_length'].median(), color=COLOR_GOLD, linestyle='--', linewidth=2, 
           label=f'Median: {df["text_length"].median():.0f} chars')
ax.axvline(df['text_length'].mean(), color=COLOR_ROSE, linestyle='-', linewidth=2, 
           label=f'Mean: {df["text_length"].mean():.0f} chars')

ax.set_title('Review Text Length Distribution', fontsize=12, pad=15, fontweight='bold', color=COLOR_PLUM)
ax.set_xlabel('Character Length (Clipped at 1,500)', fontsize=10)
ax.set_ylabel('Number of Reviews', fontsize=10)
ax.legend(fontsize=10)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.5)

# Format y-axis with comma separators
ax.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))

plt.tight_layout()
plt.savefig(figures_dir / "preprocessing_text_length.png", dpi=150, bbox_inches='tight')
plt.show()
"""))

    # Summary of final columns
    cells.append(nbf.v4.new_markdown_cell("""## 6. Summary of final ML-ready columns

Here is a summary of the 20 columns saved in the processed files, categorized by their roles in model training.

| Column Name | Data Type | Role | Imputation Strategy |
| :--- | :--- | :--- | :--- |
| **`product_id`** | string | Safe Identifier | - |
| **`author_id`** | string | Safe Identifier | - |
| **`review_text`** | string | Text Feature | Filled with `""` |
| **`review_title`** | string | Text Feature | Filled with `""` |
| **`combined_text`** | string | Engineered Text Feature | Dropped if empty |
| **`text_length`** | integer | Engineered Numeric Feature | Calculated |
| **`word_count`** | integer | Engineered Numeric Feature | Calculated |
| **`skin_type`** | string | Categorical Feature | Filled with `"unknown"` |
| **`skin_tone`** | string | Categorical Feature | Filled with `"unknown"` |
| **`hair_color`** | string | Categorical Feature | Filled with `"unknown"` |
| **`eye_color`** | string | Categorical Feature | Filled with `"unknown"` |
| **`brand_name`** | string | Categorical Feature | Filled with `"unknown"` |
| **`product_name`** | string | Categorical Feature | Filled with `"unknown"` |
| **`primary_category`** | string | Categorical Feature | Filled with `"unknown"` |
| **`secondary_category`** | string | Categorical Feature | Filled with `"unknown"` |
| **`tertiary_category`** | string | Categorical Feature | Filled with `"unknown"` |
| **`price_usd`** | float | Numeric Feature | Filled with median ($39.00) |
| **`ingredients`** | string | Text Feature | Filled with `""` |
| **`sentiment_label`** | string | 3-Class Target | Engineered |
| **`high_satisfaction`** | integer | Binary Target | Engineered |
"""))

    # Next steps
    cells.append(nbf.v4.new_markdown_cell("""## 7. Next Steps: Baseline Model Training 🚀

Now that the data has been preprocessed:
1. Leakage columns have been removed.
2. Missing values are filled.
3. Target distributions and sampling are finalized.

We are ready to move to the **`feat/baseline-model`** branch, where we will:
* Set up a text vectorization pipeline (TF-IDF vectorizer).
* Train a fast baseline classification model (Logistic Regression or Linear SVM).
* Formulate baseline metrics (Macro-F1, ROC-AUC) to address the class imbalance.
"""))

    # Save notebook structure to file
    nb['cells'] = cells
    notebook_path = root_dir / "ml" / "notebooks" / "02_data_preprocessing.ipynb"
    with open(notebook_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f"Notebook structured and saved to: {notebook_path.name}")
    
    # Execute notebook programmatically
    print("Executing notebook to populate all cells with outputs and save figures...")
    try:
        ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
        ep.preprocess(nb, {'metadata': {'path': str(root_dir / 'ml' / 'notebooks')}})
        
        # Save again with execution outputs included!
        with open(notebook_path, 'w', encoding='utf-8') as f:
            nbf.write(nb, f)
        print("Notebook executed and saved successfully with output cells populated!")
    except Exception as e:
        print(f"Error during notebook execution: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
